import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { useTranslation } from 'next-zero-intl'
import Card from '../components/card'
import ChangeLocale from '../components/change-locale'

export default function Home() {
  const { t } = useTranslation()

  return (
    <div className={styles.container}>
      <Head>
        <title>{t('Create Next App')}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {t('Pick a Language.')}
          <ChangeLocale />
        </h1>

        <p className={styles.description}>
          {t('Get started by editing')}{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <Card url="https://nextjs.org/docs" title="Documentation">
            Find in-depth information about Next.js features and API.
          </Card>
          <Card url="https://nextjs.org/learn" title="Learn">
            Learn about Next.js in an interactive course with quizzes!
          </Card>
          <Card
            url="https://github.com/vercel/next.js/tree/master/examples"
            title="Examples"
          >
            Discover and deploy boilerplate example Next.js projects.
          </Card>
          <Card
            url="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            title="Deploy"
          >
            Instantly deploy your Next.js site to a public URL with Vercel.
          </Card>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          {t('Powered by')}{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
